name: hot-ctd
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx-autodoc-typehints=1.12.0
  - sphinx-book-theme=0.2.0
  - sphinx=4.4.0
  - python=3.10
  - nbsphinx=0.8.8
  - sphinx-design=0.0.13
  - jupyterlab=3.3.3
  - myst-parser=0.17.0
  - ipython=8.1.1